# Generated by Django 3.0.7 on 2021-05-01 05:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='country',
            field=models.CharField(max_length=100, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='home_town',
            field=models.CharField(max_length=100, verbose_name='home town'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='second name'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='received_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 5, 32, 18, 611626, tzinfo=utc), verbose_name='time of receiving data'),
        ),
    ]
