# Generated by Django 3.0.7 on 2021-05-01 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandler', '0002_auto_20210501_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='city',
            field=models.CharField(max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='second name'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='received_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 5, 33, 50, 529151, tzinfo=utc), verbose_name='time of receiving data'),
        ),
    ]
