# Generated by Django 3.0.7 on 2021-05-01 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandler', '0003_auto_20210501_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='about',
            field=models.TextField(null=True, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='activities',
            field=models.TextField(null=True, verbose_name='activities'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='bdate',
            field=models.CharField(max_length=15, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='books',
            field=models.TextField(null=True, verbose_name='books'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='career',
            field=models.TextField(null=True, verbose_name='career'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='connections',
            field=models.TextField(null=True, verbose_name='connections'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='contacts',
            field=models.TextField(null=True, verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='education',
            field=models.TextField(null=True, verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='home_town',
            field=models.CharField(max_length=100, null=True, verbose_name='home town'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='received_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 5, 37, 5, 474676, tzinfo=utc), verbose_name='time of receiving data'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='status',
            field=models.TextField(null=True, verbose_name='user status'),
        ),
    ]
