# Generated by Django 3.0.7 on 2021-05-06 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandler', '0004_auto_20210501_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='home_town',
        ),
        migrations.AddField(
            model_name='userdata',
            name='city_id',
            field=models.CharField(max_length=100, null=True, verbose_name='city_id'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='city_title',
            field=models.CharField(max_length=100, null=True, verbose_name='city_title'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='country_id',
            field=models.CharField(max_length=100, null=True, verbose_name='country_id'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='country_title',
            field=models.CharField(max_length=100, null=True, verbose_name='country_title'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='home_town_id',
            field=models.CharField(max_length=100, null=True, verbose_name='home town_id'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='home_town_title',
            field=models.CharField(max_length=100, null=True, verbose_name='home town_title'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='received_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 15, 49, 48, 929648, tzinfo=utc), verbose_name='time of receiving data'),
        ),
    ]
