# Generated by Django 3.0.7 on 2021-05-06 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandler', '0005_auto_20210506_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='home_town_id',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='home_town_title',
        ),
        migrations.AddField(
            model_name='userdata',
            name='home_town',
            field=models.CharField(max_length=100, null=True, verbose_name='home town'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='received_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 16, 0, 40, 449595, tzinfo=utc), verbose_name='time of receiving data'),
        ),
    ]
