# Generated by Django 3.0.7 on 2021-05-17 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandler', '0010_auto_20210517_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='received_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 12, 26, 25, 588568, tzinfo=utc), verbose_name='time of receiving data'),
        ),
    ]
